export enum SocialProvider {
  Apple = "apple",
  Discord = "discord",
  Facebook = "facebook",
  GitHub = "github",
  Google = "google",
  Kick = "kick",
  Microsoft = "microsoft",
  TikTok = "tiktok",
  Twitch = "twitch",
  Twitter = "twitter",
  Dropbox = "dropbox",
  LinkedIn = "linkedin",
  GitLab = "gitlab",
  Reddit = "reddit",
  Roblox = "roblox",
  Spotify = "spotify",
  VK = "vk",
  Zoom = "zoom",
}

export const socialProviderNames: Record<SocialProvider, string> = {
  [SocialProvider.Apple]: "Apple",
  [SocialProvider.Discord]: "Discord",
  [SocialProvider.Facebook]: "Facebook",
  [SocialProvider.GitHub]: "GitHub",
  [SocialProvider.Google]: "Google",
  [SocialProvider.Kick]: "Kick",
  [SocialProvider.Microsoft]: "Microsoft",
  [SocialProvider.TikTok]: "TikTok",
  [SocialProvider.Twitch]: "Twitch",
  [SocialProvider.Twitter]: "Twitter",
  [SocialProvider.Dropbox]: "Dropbox",
  [SocialProvider.LinkedIn]: "LinkedIn",
  [SocialProvider.GitLab]: "GitLab",
  [SocialProvider.Reddit]: "Reddit",
  [SocialProvider.Roblox]: "Roblox",
  [SocialProvider.Spotify]: "Spotify",
  [SocialProvider.VK]: "VK",
  [SocialProvider.Zoom]: "Zoom",
};
