/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWaitingRoomWaitingRoomIdRouteImport } from './routes/_authenticated/waiting-room.$waitingRoomId'
import { Route as AuthenticatedGameGameIdRouteImport } from './routes/_authenticated/game.$gameId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaitingRoomWaitingRoomIdRoute =
  AuthenticatedWaitingRoomWaitingRoomIdRouteImport.update({
    id: '/waiting-room/$waitingRoomId',
    path: '/waiting-room/$waitingRoomId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGameGameIdRoute = AuthenticatedGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/waiting-room/$waitingRoomId': typeof AuthenticatedWaitingRoomWaitingRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/waiting-room/$waitingRoomId': typeof AuthenticatedWaitingRoomWaitingRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/_authenticated/waiting-room/$waitingRoomId': typeof AuthenticatedWaitingRoomWaitingRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$gameId' | '/waiting-room/$waitingRoomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$gameId' | '/waiting-room/$waitingRoomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/game/$gameId'
    | '/_authenticated/waiting-room/$waitingRoomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waiting-room/$waitingRoomId': {
      id: '/_authenticated/waiting-room/$waitingRoomId'
      path: '/waiting-room/$waitingRoomId'
      fullPath: '/waiting-room/$waitingRoomId'
      preLoaderRoute: typeof AuthenticatedWaitingRoomWaitingRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/game/$gameId': {
      id: '/_authenticated/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof AuthenticatedGameGameIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedGameGameIdRoute: typeof AuthenticatedGameGameIdRoute
  AuthenticatedWaitingRoomWaitingRoomIdRoute: typeof AuthenticatedWaitingRoomWaitingRoomIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGameGameIdRoute: AuthenticatedGameGameIdRoute,
  AuthenticatedWaitingRoomWaitingRoomIdRoute:
    AuthenticatedWaitingRoomWaitingRoomIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
