/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  index: {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/jazz/examples/button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/jazz/examples/button-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "button/with-icon": {
    name: "button/with-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/jazz/examples/button/with-icon.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/jazz/examples/button/with-icon.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "button/kitchen-sink": {
    name: "button/kitchen-sink",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/jazz/examples/button/kitchen-sink.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/jazz/examples/button/kitchen-sink.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
